spring.application.name=oparea
# URL de conexión a la base de datos
spring.datasource.url=jdbc:sqlserver://163.178.173.130;databaseName=ZenithSky_C4i431_1_2026;encrypt=true;trustServerCertificate=true;
spring.datasource.username=Lenguajes
spring.datasource.password=lenguajesparaiso2025
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

server.port =8084
